Expose the greet service to the outside world via an ingress resource. Use name-based virtual hosting. 
Name the ingress greet-ingress. Set the host to kubeacademy-w06-s114-greet.acad-kube-prd1.labs.kube.academy. 
The ingress backend should map to your internal greet ClusterIP service running on port 8080.

[~] $ kubectl create ingress greet-ingress --rule=kubeacademy-w06-s115-greet.acad-kube-prd1.labs.kube.academy/*=greet:8080 --dry-run=client -o yaml > greet-ingress.yaml
[~] $ cat greet-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: greet-ingress
spec:
  rules:
  - host: kubeacademy-w06-s115-greet.acad-kube-prd1.labs.kube.academy
    http:
      paths:
      - backend:
          service:
            name: greet
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
