Apply the deployment named cara:

k apply -f services-and-networking/cara.yaml
Challenge
Expose the deployment (which is running on port 8080) 
using a NodePort type service named cara using the service port 31888.

[~] $ k create svc nodeport cara --tcp=8080:8080 --node-port=31888 --dry-run=client -o yaml > cara-svc.yaml
[~] $ cat cara-svc.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cara
  name: cara
spec:
  ports:
  - name: 8080-8080
    nodePort: 31888
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cara
  type: NodePort
status:
  loadBalancer: {}