Create a ClusterIP service for pod ig-11 named greet. Map service port 8080 to container port 8080.

[~] $ k expose pod ig-11 --type='ClusterIP' --port=8080 --target-port=8080 --name=greet --dry-run=client -o yaml > greet-svc.yaml


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ig-11
  name: greet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: ig-11
  type: ClusterIP
status:
  loadBalancer: {}