Create a pod named ig-11 with image bitnami/nginx and specifying the container port 8080.

[~] $ k run ig-11 --image=bitnami/nginx --port=8080 --dry-run=client -o yaml > ig-11.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ig-11
  name: ig-11
spec:
  containers:
  - image: bitnami/nginx
    name: ig-11
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}