# Create a Pod named secure-pod. Use the bitnami/redis image. Run pod as user 1000 and group 2000.

# k run secure-pod --image=bitnami/redis --env=REDIS_PASSWORD=howdy $DR | tee secure-pod.yaml


apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secure-pod
  name: secure-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - env:
    - name: REDIS_PASSWORD
      value: howdy
    image: bitnami/redis
    name: secure-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

