# Create a Pod named httptest with image mccutchen/go-httpbin and a readiness probe 
# that checks the http endpoint of the container at path /status/200 on port 8080.

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httptest
  name: httptest
spec:
  containers:
  - image: mccutchen/go-httpbin
    name: httptest
    resources: {}
    readinessProbe:
      httpGet:
        path: /status/200
        port: 8080
      initialDelaySeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}